version: 1.0.{build}

build: off
clone_folder: c:\go\src\github.com\koooge\redash-sdk-go
shallow_clone: true

install:
  - go get -v ./redash/...
before_test:
  - go vet -v ./redash/...
test_script:
  - go test -v -cover ./redash/...
