
openapi: 3.0.2
info:
  title: redash
  version: 0.0.1
paths:
  /ping:
    get:
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: PONG.
  /status.json:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  dashboards_count:
                    type: integer
                  database_metrics:
                    type: object
                    properties:
                      metrics:
                        type: array
                        items:
                          type: array
                          items:
                            oneOf:
                              - type: string
                              - type: integer
                  manager:
                    type: object
                    properties:
                      last_refresh_at:
                        type: string
                      outdated_queries_count:
                        type: string
                      query_ids:
                        type: string
                      queues:
                        type: object
                        properties:
                          celery:
                            type: object
                            properties:
                              data_sources:
                                type: string
                              size:
                                type: integer
                  queries_count:
                    type: integer
                  query_results_count:
                    type: integer
                  redis_used_memory:
                    type: integer
                  redis_used_memory_human:
                    type: string
                  unused_query_results_count:
                    type: integer
                  version:
                    type: string
                  widgets_count:
                    type: integer
                  workers:
                    type: array
                    items: {}
  /api/users:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_type:
                    type: string
                  is_disabled:
                    type: boolean
                  updated_at:
                    type: string
                  profile_image_url:
                    type: string
                    format: uri
                  is_invitation_pending:
                    type: boolean
                  groups:
                    type: array
                    items:
                      type: integer
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                  disabled_at:
                    type: string
                    nullable: true
                  invite_link:
                    type: string
                    format: uri
                  active_at:
                    type: string
                    nullable: true
                  email:
                    type: string
                    format: email
        400:
          description: Bad Request
          content:
            applicatin/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
