openapi: 3.0.2
info:
  title: redash
  version: 0.0.1
paths:
  /ping:
    get:
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: PONG.
  /status.json:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  dashboards_count:
                    type: integer
                  database_metrics:
                    type: object
                    properties:
                      metrics:
                        type: array
                        items:
                          type: array
                          items:
                            oneOf:
                              - type: string
                              - type: integer
                  manager:
                    type: object
                    properties:
                      last_refresh_at:
                        type: string
                      outdated_queries_count:
                        type: string
                      query_ids:
                        type: string
                      queues:
                        type: object
                        properties:
                          celery:
                            type: object
                            properties:
                              data_sources:
                                type: string
                              size:
                                type: integer
                  queries_count:
                    type: integer
                  query_results_count:
                    type: integer
                  redis_used_memory:
                    type: integer
                  redis_used_memory_human:
                    type: string
                  unused_query_results_count:
                    type: integer
                  version:
                    type: string
                  widgets_count:
                    type: integer
                  workers:
                    type: array
                    items: {}
  /api/datasources:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    pause_reason:
                      type: string
                      nullable: true
                    syntex:
                      type: string
                    paused:
                      type: integer
                    view_only:
                      type: boolean
                    type:
                      type: string
                    id:
                      type: integer
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                options:
                  type: object
                  properties:
                    dbname:
                      type: string
                name:
                  type: string
                type:
                  type: string
              required:
                - options
                - name
                - email
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  scheduled_queue_name:
                    type: string
                  name:
                    type: string
                  pause_reason:
                    type: string
                    nullable: true
                  queue_name:
                    type: string
                  syntax:
                    type: string
                  paused:
                    type: integer
                  options:
                    type: object
                    properties:
                      dbname:
                        type: string
                  groups:
                    type: object
                    properties:
                      2:
                        type: boolean
                  type:
                    type: string
                  id:
                    type: integer
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/query_results:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                query_id:
                  type: number
                max_age:
                  type: number
                data_source_id:
                  type: number
                parameters:
                  type: object
                  properties:
                    param:
                      type: integer
              required:
                - query
                - data_source_id
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  job:
                    type: object
                    properties:
                      status:
                        type: integer
                      error:
                        type: string
                      id:
                        type: string
                      query_result_id:
                        type: integer
                        nullable: true
                      updated_at:
                        type: integer
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/users:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: page_size
          schema:
            type: integer
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: disabled
          schema:
            type: boolean
          allowEmptyValue: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  page:
                    type: integer
                  page_size:
                    type: integer
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        auth_type:
                          type: string
                        is_disabled:
                          type: boolean
                        updated_at:
                          type: string
                          format: date-time
                        profile_image_url:
                          type: string
                          format: uri
                        is_invitation_pending:
                          type: boolean
                        groups:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                        id:
                          type: integer
                        name:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                        disabled_at:
                          type: string
                          format: date-time
                          nullable: true
                        actived_at:
                          type: string
                          format: date-time
                          nullable: true
                        email:
                          type: string
                          format: email
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: emai
              required:
                - name
                - email
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_type:
                    type: string
                  is_disabled:
                    type: boolean
                  updated_at:
                    type: string
                    format: date-time
                  profile_image_url:
                    type: string
                    format: uri
                  is_invitation_pending:
                    type: boolean
                  groups:
                    type: array
                    items:
                      type: integer
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  disabled_at:
                    type: string
                    format: date-time
                    nullable: true
                  invite_link:
                    type: string
                    format: uri
                  active_at:
                    type: string
                    format: date-time
                    nullable: true
                  email:
                    type: string
                    format: email
        400:
          description: Bad Request
          content:
            applicatin/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
