openapi: 3.0.2
info:
  title: redash
  version: 0.0.1
paths:
  /ping:
    get:
      responses:
        200:
          description: ping
          content:
            text/html:
              schema:
                type: string
                example: PONG.
