name: Test

# TODO: test on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.17']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Lint
      run: |
        go vet ./redash/...
        test `gofmt -l . | wc -l` = 0

    - name: Test and Coverage
      run: |
        go test -coverprofile=cover.out -covermode=count ./redash/...

    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: cover.out:gocov
        prefix: github.com/koooge/redash-sdk-go
